CREATE TABLE IF NOT EXISTS category(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK (name <> ''),
    image_url text 
);

CREATE TABLE IF NOT EXISTS users(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	username text NOT NULL CHECK (username <> ''),
    password text NOT NULL CHECK (password <> ''),
	email text,
	contact_information text,
	role integer
);

CREATE TABLE IF NOT EXISTS payment_methods(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	type_method text,
    data text,
	userid integer references users(id)
);

-- NO OYE, NO LO PUSISTE
CREATE TABLE IF NOT EXISTS items(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	productid integer NOT NULL REFERENCES products(id),
  	shopping_cartid integer NOT NULL REFERENCES shopping_carts(id),
	amount integer NOT NULL CHECK (amount>=0),
	final_price real not null
);

CREATE TABLE IF NOT EXISTS shopping_carts(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	sales_price real not null,
	date_created  date
);

CREATE TABLE IF NOT EXISTS orders(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	sales_price real not null,
	date_created  date,
	date_dispatched date,
	date_delivered  date,
	date_received  date,
	date_cancelled  date,
	shopping_cartid integer NOT NULL REFERENCES shopping_carts(id),
	payment_methodid integer REFERENCES payment_methods(id),
	userid integer NOT NULL REFERENCES users(id),
	status  text
);

INSERT INTO categories(name,image_url) VALUES ('Nendoroid','https://i.imgur.com/nP1DV2V.jpg')
INSERT INTO categories(name,image_url) VALUES ('Figuras PVC','https://i.imgur.com/v4YRpKC.jpg')
INSERT INTO categories(name,image_url) VALUES ('Funko Pop','https://i.imgur.com/WrUJw6M.jpg')
INSERT INTO categories(name,image_url) VALUES ('Peluches','https://i.imgur.com/pttrEfG.jpg')


-- REINICIAR TABLA ID {nombre_tabla}_{columna}_seq
ALTER SEQUENCE products_id_seq RESTART WITH 1


CREATE TABLE IF NOT EXISTS products(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	code text,
	name text NOT NULL CHECK (name <> ''),
	description text,
	stock integer NOT NULL CHECK (stock>=0),
	price real not null,
    image_url text 
);

CREATE TABLE IF NOT EXISTS addresses(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	street TEXT,
	city TEXT,
	country TEXT,
	post_code TEXT,
	user_id integer NOT NULL REFERENCES users(id),
);

CREATE TABLE IF NOT EXISTS category_product(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	product_id integer NOT NULL REFERENCES products(id),
  	category_id integer NOT NULL REFERENCES categories(id),
)



INSERT INTO category_product(product_id,category_id) VALUES (1,1)
INSERT INTO category_product(product_id,category_id) VALUES (2,1)
INSERT INTO category_product(product_id,category_id) VALUES (3,1)
INSERT INTO category_product(product_id,category_id) VALUES (4,1)
INSERT INTO category_product(product_id,category_id) VALUES (5,1)

INSERT INTO category_product(product_id,category_id) VALUES (6,2);
INSERT INTO category_product(product_id,category_id) VALUES (7,2);
INSERT INTO category_product(product_id,category_id) VALUES (8,2);
INSERT INTO category_product(product_id,category_id) VALUES (9,2);
INSERT INTO category_product(product_id,category_id) VALUES (10,2);
INSERT INTO category_product(product_id,category_id) VALUES (21,2);
INSERT INTO category_product(product_id,category_id) VALUES (22,2);

INSERT INTO category_product(product_id,category_id) VALUES (11,3);
INSERT INTO category_product(product_id,category_id) VALUES (12,3);
INSERT INTO category_product(product_id,category_id) VALUES (13,3);
INSERT INTO category_product(product_id,category_id) VALUES (14,3);
INSERT INTO category_product(product_id,category_id) VALUES (15,3);

INSERT INTO category_product(product_id,category_id) VALUES (16,4);
INSERT INTO category_product(product_id,category_id) VALUES (17,4);
INSERT INTO category_product(product_id,category_id) VALUES (18,4);
INSERT INTO category_product(product_id,category_id) VALUES (19,4);
INSERT INTO category_product(product_id,category_id) VALUES (20,4);


-- CONSULTA QUE RETORNA LOS PRODUCTOS QUE MACHEAN CON EL NOMBRE DE LA CATEGORIA
SELECT * FROM products
WHERE id IN (
	SELECT productId FROM category_products
	WHERE categoryId in (
		SELECT id FROM categories
		WHERE name = 'Figuras PVC'
	)
)

SELECT * FROM products
WHERE id IN (
	SELECT productId FROM product_promos
	WHERE promosId in (
		SELECT id FROM promos
		WHERE NOW()>=date_start and NOW()<=date_finish
	)
)


CREATE TABLE IF NOT EXISTS promos(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	name text,
	description text,
	date_start date ,
	date_finish date,
	discount real ,
)


CREATE TABLE IF NOT EXISTS product_promos(
	id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
	product_id integer NOT NULL REFERENCES products(id),
  	promos_id integer NOT NULL REFERENCES promos(id),
)